export const ADD_SURVEY = 'ADD_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const TOGGLE_EDIT_FORM = 'TOGGLE_EDIT_FORM';
export const SELECT_SURVEY = 'SELECT_SURVEY';
export const RESET_SURVEY = 'RESET_SURVEY';